[package]
name = "astexplorer-gleam"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2.80"
gleam-core = { version = "=0.21.0-rc1", path = "gleam/compiler-core" }

[profile.release]
opt-level = "z"
lto = true
